/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Model.Address;
import Model.Contact;
import Model.Person;

/**
 *
 * @author Nidhi Raghavendra
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    private Person person;
    
    public MainJFrame() {
        initComponents();
        
        this.person = new Person();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        CreateJPanel = new javax.swing.JPanel();
        fieldName = new javax.swing.JTextField();
        fieldStreet = new javax.swing.JTextField();
        SaveBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        officePhone = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        permStreet1 = new javax.swing.JTextField();
        localPhone1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        officeEmail = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        personalEmail1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        fieldAptNum = new javax.swing.JTextField();
        fieldCity = new javax.swing.JTextField();
        fieldState = new javax.swing.JTextField();
        fieldZipCode = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        permAptNum = new javax.swing.JTextField();
        permCity1 = new javax.swing.JTextField();
        permState1 = new javax.swing.JTextField();
        permZipCode1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        fieldCollegeName = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        fieldNUID = new javax.swing.JTextField();
        ViewJPanel = new javax.swing.JPanel();
        viewName = new javax.swing.JLabel();
        viewStreet = new javax.swing.JLabel();
        viewPermAddre = new javax.swing.JLabel();
        viewPersonalPhone = new javax.swing.JLabel();
        viewOfficePhone = new javax.swing.JLabel();
        viewPersonalEmail = new javax.swing.JLabel();
        viewOffieEmail = new javax.swing.JLabel();
        viewAptNumber = new javax.swing.JLabel();
        viewCity = new javax.swing.JLabel();
        viewState = new javax.swing.JLabel();
        viewZipCode = new javax.swing.JLabel();
        viewNUID = new javax.swing.JLabel();
        viewCollegeName = new javax.swing.JLabel();
        viewPermAptNumber = new javax.swing.JLabel();
        viewPermCity = new javax.swing.JLabel();
        viewPermState = new javax.swing.JLabel();
        viewPermZipCode = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CreateJPanel.setBackground(new java.awt.Color(204, 204, 255));
        CreateJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        CreateJPanel.add(fieldName, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 124, 37));
        CreateJPanel.add(fieldStreet, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 124, 36));

        SaveBtn.setText("SAVE");
        SaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveBtnActionPerformed(evt);
            }
        });
        CreateJPanel.add(SaveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 530, -1, -1));

        jLabel3.setText("Name");
        CreateJPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 20));

        jLabel4.setText("Permanent street");
        CreateJPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, -1, -1));
        CreateJPanel.add(officePhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 430, 130, 31));

        jLabel5.setText("Street");
        CreateJPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));
        CreateJPanel.add(permStreet1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, 120, 40));
        CreateJPanel.add(localPhone1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, 130, 31));

        jLabel6.setText("Office Phone");
        CreateJPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, -1, -1));

        jLabel7.setText("Personal Phone");
        CreateJPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, -1, -1));
        CreateJPanel.add(officeEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 430, 130, 31));

        jLabel8.setText("Office Email");
        CreateJPanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 440, -1, -1));
        CreateJPanel.add(personalEmail1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 380, 130, 31));

        jLabel9.setText("Personal Email");
        CreateJPanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 390, -1, -1));
        CreateJPanel.add(fieldAptNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 130, 40));
        CreateJPanel.add(fieldCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 70, 40));
        CreateJPanel.add(fieldState, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 70, 40));
        CreateJPanel.add(fieldZipCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 90, 40));

        jLabel1.setText("Apt NO.");
        CreateJPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        jLabel2.setText("City");
        CreateJPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        jLabel10.setText("State");
        CreateJPanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, -1, -1));

        jLabel11.setText("Zip Code");
        CreateJPanel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        jLabel12.setText("Permanent Apt NO.");
        CreateJPanel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, -1, -1));

        jLabel13.setText("Permanent City");
        CreateJPanel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, -1, -1));

        jLabel14.setText("Permanent State");
        CreateJPanel.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, -1, -1));
        CreateJPanel.add(permAptNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, 120, 40));
        CreateJPanel.add(permCity1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, 80, 40));
        CreateJPanel.add(permState1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 260, 80, 40));
        CreateJPanel.add(permZipCode1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 320, 90, 30));

        jLabel15.setText("Permanent Zip Code");
        CreateJPanel.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, -1, -1));
        CreateJPanel.add(fieldCollegeName, new org.netbeans.lib.awtextra.AbsoluteConstraints(334, 13, 110, 30));

        jLabel16.setText("College");
        CreateJPanel.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        jLabel17.setText("NUID");
        CreateJPanel.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));
        CreateJPanel.add(fieldNUID, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 63, 120, 30));

        jSplitPane1.setLeftComponent(CreateJPanel);

        ViewJPanel.setBackground(new java.awt.Color(255, 204, 204));
        ViewJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        viewName.setText("Name");
        ViewJPanel.add(viewName, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, -1));

        viewStreet.setText("Street");
        ViewJPanel.add(viewStreet, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, -1, -1));

        viewPermAddre.setText("Perm Address");
        ViewJPanel.add(viewPermAddre, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, -1, 20));

        viewPersonalPhone.setText("PersonalPhone");
        ViewJPanel.add(viewPersonalPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, -1, -1));

        viewOfficePhone.setText("OfficePhone");
        ViewJPanel.add(viewOfficePhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 440, -1, -1));

        viewPersonalEmail.setText("PersonalEmail");
        ViewJPanel.add(viewPersonalEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 380, -1, -1));

        viewOffieEmail.setText("OfficeEmail");
        ViewJPanel.add(viewOffieEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 440, -1, -1));

        viewAptNumber.setText("AptNumber");
        ViewJPanel.add(viewAptNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, -1));

        viewCity.setText("City");
        ViewJPanel.add(viewCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, -1, -1));

        viewState.setText("State");
        ViewJPanel.add(viewState, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, -1, -1));

        viewZipCode.setText("Zip Code");
        ViewJPanel.add(viewZipCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, -1, -1));

        viewNUID.setText("NUID");
        ViewJPanel.add(viewNUID, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, -1));

        viewCollegeName.setText("College");
        ViewJPanel.add(viewCollegeName, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 60, 20));

        viewPermAptNumber.setText("Perm Apt Number");
        ViewJPanel.add(viewPermAptNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, -1, -1));

        viewPermCity.setText("Perm City");
        ViewJPanel.add(viewPermCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, -1, -1));

        viewPermState.setText("Perm State");
        ViewJPanel.add(viewPermState, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, -1, -1));

        viewPermZipCode.setText("Perm Zip Code");
        ViewJPanel.add(viewPermZipCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, -1, -1));

        jSplitPane1.setRightComponent(ViewJPanel);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveBtnActionPerformed
        // TODO add your handling code here:
        String name = fieldName.getText();
        String collegeName = fieldCollegeName.getText();
        long NUID = Long.valueOf(fieldNUID.getText());
        
        String street = fieldStreet.getText();
        String permStreet = permStreet1.getText();
        
        String aptNumber = fieldAptNum.getText();
        String permAptNumber = permAptNum.getText();
        
        String city = fieldCity.getText();
        String permCity = permCity1.getText();
        
        String state = fieldState.getText();
        String permState = permState1.getText();
        
        String zipCode = fieldZipCode.getText();
        String permZipCode = permZipCode1.getText();
        
        long localPhone = Long.valueOf(localPhone1.getText());
        long offPhone = Long.valueOf(officePhone.getText());
        String personalEmail = personalEmail1.getText();
        String offEmail = officeEmail.getText();
        
        this.person.setName(name);
        person.setCollegeName(collegeName);
        person.setNUID(NUID);
        
        Address address = this.person.getAddress();
        address.setStreet(street);
        address.setAptNumber(aptNumber);
        address.setCity(city);
        address.setState(state);
        address.setZipCode(zipCode);
        
        
        Address permanentAddress = this.person.getPermanentAddress();
        permanentAddress.setStreet(permStreet);
        permanentAddress.setAptNumber(permAptNumber);
        permanentAddress.setCity(permCity);
        permanentAddress.setState(permState);
        permanentAddress.setZipCode(permZipCode);
        
        Contact officeContact = this.person.getOfficeContact();
        officeContact.setPhoneNumber(offPhone);
        officeContact.setEmailID(offEmail);
        
        Contact locatContact = this.person.getPersonalContact();
        locatContact.setPhoneNumber(localPhone);
        locatContact.setEmailID(personalEmail);
        
        display();
    }//GEN-LAST:event_SaveBtnActionPerformed

    private void display() {
        viewName.setText(this.person.getName());
        viewCollegeName.setText(this.person.getCollegeName());
        viewNUID.setText(String.valueOf(this.person.getNUID()));
        
        viewStreet.setText(this.person.getAddress().getStreet());
        viewAptNumber.setText(this.person.getAddress().getAptNumber());
        viewCity.setText(this.person.getAddress().getCity());
        viewState.setText(this.person.getAddress().getState());
        viewZipCode.setText(this.person.getAddress().getZipCode());
        
        viewPermAddre.setText(this.person.getPermanentAddress().getStreet());
        viewPermAptNumber.setText(this.person.getPermanentAddress().getAptNumber());
        viewPermCity.setText(this.person.getPermanentAddress().getCity());
        viewPermState.setText(this.person.getPermanentAddress().getState());
        viewPermZipCode.setText(this.person.getPermanentAddress().getZipCode());
        
        viewPersonalPhone.setText(String.valueOf(this.person.getPersonalContact().getPhoneNumber()));
        viewOfficePhone.setText(String.valueOf(this.person.getPersonalContact().getPhoneNumber()));
        
        viewPersonalEmail.setText(this.person.getPersonalContact().getEmailID());
        viewOffieEmail.setText(this.person.getOfficeContact().getEmailID());
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CreateJPanel;
    private javax.swing.JButton SaveBtn;
    private javax.swing.JPanel ViewJPanel;
    private javax.swing.JTextField fieldAptNum;
    private javax.swing.JTextField fieldCity;
    private javax.swing.JTextField fieldCollegeName;
    private javax.swing.JTextField fieldNUID;
    private javax.swing.JTextField fieldName;
    private javax.swing.JTextField fieldState;
    private javax.swing.JTextField fieldStreet;
    private javax.swing.JTextField fieldZipCode;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextField localPhone1;
    private javax.swing.JTextField officeEmail;
    private javax.swing.JTextField officePhone;
    private javax.swing.JTextField permAptNum;
    private javax.swing.JTextField permCity1;
    private javax.swing.JTextField permState1;
    private javax.swing.JTextField permStreet1;
    private javax.swing.JTextField permZipCode1;
    private javax.swing.JTextField personalEmail1;
    private javax.swing.JLabel viewAptNumber;
    private javax.swing.JLabel viewCity;
    private javax.swing.JLabel viewCollegeName;
    private javax.swing.JLabel viewNUID;
    private javax.swing.JLabel viewName;
    private javax.swing.JLabel viewOfficePhone;
    private javax.swing.JLabel viewOffieEmail;
    private javax.swing.JLabel viewPermAddre;
    private javax.swing.JLabel viewPermAptNumber;
    private javax.swing.JLabel viewPermCity;
    private javax.swing.JLabel viewPermState;
    private javax.swing.JLabel viewPermZipCode;
    private javax.swing.JLabel viewPersonalEmail;
    private javax.swing.JLabel viewPersonalPhone;
    private javax.swing.JLabel viewState;
    private javax.swing.JLabel viewStreet;
    private javax.swing.JLabel viewZipCode;
    // End of variables declaration//GEN-END:variables
}
